### ISSUE TITLE
Make League Sign-up UI Responsive

### ISSUE THREAD

**Issue by kapilace6** [indianracingcommunity/RLIProject#102]
End goal is for drivers to be able to sign up using their mobile devices.

**Comment by nitishapiplani** [comment]
I WOULD LIKE TO DO THIS

**Comment by kapilace6** [comment]
Hi @nitishapiplani , thank you reaching out. However, Collaboration is only open to community members and not open to the public right now.

**Comment by kapilace6** [comment]
Implemented in https://github.com/indianracingcommunity/RLIProject/commit/73df3ac3de442bc4aa17be32f86801d6b6f7082a
Released in v5.1.2
