### ISSUE TITLE
Record the operations of setting the project from scratch.

### ISSUE THREAD

**Issue by kapilace6** [indianracingcommunity/RLIProject#96]
Document the process of setting up while migrating the project into the new cloud account

**Comment by TheFreeman15** [comment]
Why add this documentation in the code since its gonna be obsolete when the docker integration is complete

**Comment by kapilace6** [comment]
To have a reference, and to revert to a non-docker state if required.
You've already made the documentation, so it's just a matter of making it visible to all new collaborators.
